name: future_button
description: Buttons with progress bars
version: 0.0.1
author: kekland <kk.erzhan@gmail.com>
homepage: https://github.com/kekland/future_button
repository: https://github.com/kekland/future_button
issue_tracker: https://github.com/kekland/future_button/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
